<a href="https://colab.research.google.com/github/wekann/Assignment/blob/assignment-3/ASSIGNMENT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1) Create a Numpy Array "arr" of integers 0 to 5 and print its data type.
#You can create a NumPy array containing integers from 0 to 5 like this:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)



int64


In [ ]:
# Q2) Given a Numpy array "arr",check if its data type is float64.
        # arr = np.array(1.5,2.6,3.7)

import numpy as np
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == np.float64:
    print("The data type of arr is float64.")
else:
    print("The data type of arr is not float64.")

The data type of arr is float64.


In [ ]:
# Q3) Create a Numpy array "arr" with a data type of complex128 containing three complex numbers.
import numpy as np
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print("Data type of arr:", arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
Data type of arr: complex128


In [ ]:
# Q4) Convert an existing Numpy array "arr" of integers to float32 data types.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print("Original array:", arr)
print("Array with float32 data type:", arr_float32)

Original array: [1 2 3 4 5]
Array with float32 data type: [1. 2. 3. 4. 5.]


In [ ]:
# Q5) Given a Numpy array "arr" with float64 data type ,convert it to float32 to reduce decimal precision.
import numpy as np
arr = np.array([1.23456789, 2.3456789, 3.456789, 4.56789, 5.6789], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("Original array:", arr)
print("Array with float32 data type:", arr_float32)

Original array: [1.23456789 2.3456789  3.456789   4.56789    5.6789    ]
Array with float32 data type: [1.2345679 2.3456788 3.456789  4.56789   5.6789   ]


In [ ]:
# Q6) Write a function array_attributes that takes a Numpy Array as input and returns its shape,size and data type.
import numpy as np
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
# Q7) Create a function array_dimension that takes a numpy array as input and return its dimensionality.
import numpy as np
def array_dimension(arr):
    return arr.ndim
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Dimensionality of arr_1d:", array_dimension(arr_1d))
print("Dimensionality of arr_2d:", array_dimension(arr_2d))
print("Dimensionality of arr_3d:", array_dimension(arr_3d))

Dimensionality of arr_1d: 1
Dimensionality of arr_2d: 2
Dimensionality of arr_3d: 3


In [ ]:
# Q8) Design a function item_size_info that takes a Numpy array as an input and returns the item size and the total size in bytes.
import numpy as np
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print("Item size:", item_size, "bytes")
print("Total size:", total_size, "bytes")

Item size: 4 bytes
Total size: 24 bytes


In [ ]:
# Q9) Create a function array_strides that takes a Numpy array as input and returns the strides of an array.
import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)
print("Strides:", strides)

Strides: (12, 4)


In [ ]:
# Q10) Design a function shape_stride_relationship that takes a Numpy array as input and returns the shape and strides of the array.
import numpy as np
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


In [ ]:
# Q11) Create a function "create_zeros_array" that takes an integers "n" as input and returns a Numpy Array of zeros with "n" elements.
import numpy as np
def create_zeros_array(n):
    return np.zeros(n)
n = 5
zeros_array = create_zeros_array(n)
print("Zeros array with", n, "elements:", zeros_array)

Zeros array with 5 elements: [0. 0. 0. 0. 0.]


In [ ]:
# Q12) Write a function "create_ones_matrix" that takes integers "rows" and "cols" as inputs and generates a 2D Numpy array filled with ones of size "rows x cols."
import numpy as np
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Ones matrix of size", rows, "x", cols, ":\n", ones_matrix)

Ones matrix of size 3 x 4 :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Q13) Write a function "generates_range_array"that takes three integers start,stop and step as arguments and creates a Numpy array with a range starting from "start", ending at "stop"(exclusive),and with the specified "step".
import numpy as np
def generates_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = 1
stop = 10
step = 2
range_array = generates_range_array(start, stop, step)
print("Generated array:", range_array)

Generated array: [1 3 5 7 9]


In [ ]:
# Q14) Design a function "generates_linear_space"that takes two floats start,stop and an integer "num" as arguments and creates a Numpy array with num equally spaced values between "start"and "stop".
import numpy as np
def generates_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
start = 1.0
stop = 5.0
num = 7
linear_space_array = generates_linear_space(start, stop, num)
print("Generated linear space array:", linear_space_array)

Generated linear space array: [1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]


In [ ]:
# Q15) Create a function "create_identity_matrix"that takes an integer "n" as input and generates a square identity matrix of size "n * n" using "numpy.exe"
import numpy as np
def create_identity_matrix(n):
    return np.eye(n)
n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix of size", n, "x", n, ":\n", identity_matrix)

Identity matrix of size 4 x 4 :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Q16) Write a function that takes a Python list and converts it into a Numpy Array.
import numpy as np
def list_to_numpy_array(input_list):
    return np.array(input_list)
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print("NumPy array from Python list:", numpy_array)

NumPy array from Python list: [1 2 3 4 5]


In [ ]:
# Q17) Create a Numpy Array and demonstrate the use "numpy.view" to create a new array object with the same data.
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array.view(dtype=np.float32)
view_array[0] = 0.5
print("Original array:", original_array)
print("View array:", view_array)

Original array: [1056964608          2          3          4          5]
View array: [5.e-01 0.e+00 3.e-45 0.e+00 4.e-45 0.e+00 6.e-45 0.e+00 7.e-45 0.e+00]


In [ ]:
# Q18) Write a function that takes two Numpy arrays and concatenates them along a specified axis.
import numpy as np
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate_arrays((array1, array2), axis=axis)
array1 = np.array[[1, 2],[3, 4]]
array2 = np.array[[5, 6]]
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0:\n", concatenated_array)
concatenated_array = concatenate_arrays(array1, array2, axis=1)
print("Concatenated array along axis 1:\n", concatenated_array)

TypeError: tuple indices must be integers or slices, not tuple

In [ ]:
# Q19) Create two Numpy arrays with different shapes and concatenates them horizontally using "numpy.concatenates"
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7],
                   [8]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array horizontally:\n", concatenated_array)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[7]
 [8]]
Concatenated array horizontally:
 [[1 2 3 7]
 [4 5 6 8]]


In [ ]:
# Q20) Write a function that vertically stacks multiple Numpy arrays given as a list.
import numpy as np
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])
stacked_array = stack_arrays_vertically([array1, array2, array3])
print("Stacked array vertically:\n", stacked_array)

Stacked array vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# Q21) Write a python function using Numpy to create an array of integers within a specified range(inclusive) with a given step size.
import numpy as np
def create_integer_array(start, stop, step):
    return np.arange(start, stop + 1, step, dtype=int)
start = 1
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)
print("Array of integers within the range [{}, {}] with step {}: {}".format(start, stop, step, integer_array))

Array of integers within the range [1, 10] with step 2: [1 3 5 7 9]


In [ ]:
# Q22) Write a python function using Numpy to create an array of 10 equally spaced value between 0 and 1 (inclusive).
import numpy as np
def create_equally_spaced_array(start, stop, num):
    return np.linspace(start, stop, num)
start = 0
stop = 1
num = 10
equally_spaced_array = create_equally_spaced_array(start, stop, num)
print("Array of {} equally spaced values between {} and {} (inclusive):\n{}".format(num, start, stop, equally_spaced_array))

Array of 10 equally spaced values between 0 and 1 (inclusive):
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# Q23) Write a python function using Numpy to create an array of 5 logarithmically spaced values between 1 and 1000.(inclusive)
import numpy as np
def create_logarithmically_spaced_array(start, stop, num):
    return np.logspace(np.log10(start), np.log10(stop), num)
start = 1
stop = 1000
num = 5
log_spaced_array = create_logarithmically_spaced_array(start, stop, num)
print("Array of {} logarithmically spaced values between {} and {} (inclusive):\n{}".format(num, start, stop, log_spaced_array))

Array of 5 logarithmically spaced values between 1 and 1000 (inclusive):
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# Q24) Create a Pandas Dataframe using a Numpy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd
np.random.seed(0)
random_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(random_array, columns=['Column 1', 'Column 2', 'Column 3'])
print("Pandas DataFrame:")
print(df)

Pandas DataFrame:
   Column 1  Column 2  Column 3
0        45        48        65
1        68        68        10
2        84        22        37
3        88        71        89
4        89        13        59


In [ ]:
# Q25) Write a function that takes a Pandas Dataframes and replaces all negative values in a specific column with zeros. Use Numpy operations within the Pandas Dataframes.
import pandas as pd
def replace_negative_with_zeros(dataframe, column_name):
    dataframe[column_name] = dataframe[column_name].apply(lambda x: max(0, x))
    return dataframe
data = {'A': [1, 2, 3, -4, 5],
        'B': [-10, 20, 30, -40, 50],
        'C': [100, -200, 300, 400, -500]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
column_name = 'B'
df_modified = replace_negative_with_zeros(df, column_name)
print("\nDataFrame with negative values in column '{}' replaced with zeros:".format(column_name))
print(df_modified)

Original DataFrame:
   A   B    C
0  1 -10  100
1  2  20 -200
2  3  30  300
3 -4 -40  400
4  5  50 -500

DataFrame with negative values in column 'B' replaced with zeros:
   A   B    C
0  1   0  100
1  2  20 -200
2  3  30  300
3 -4   0  400
4  5  50 -500


In [ ]:
# Q26) Access the 3rd element from the given Numpy Array.
     #arr = np.array([10,20,30,40,50])
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("Third element from the array:", third_element)

Third element from the array: 30


In [ ]:
#Q27) Retrieve the element at index(1,2) from 2D Numpy Array.
#arr_2d = np.array([[1,2,3],
#                 [4,5,6],
#                 [7,8,9]])
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element_12 = arr_2d[1, 2]
print("Element at index (1, 2):", element_12)

Element at index (1, 2): 6


In [ ]:
# Q28) Using boolean indexing , extract elements greater than 5 from the given Numpy Array.
#arr = np.array([3,8,2,10,5,7])
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", greater_than_5)

Elements greater than 5: [ 8 10  7]


In [ ]:
# Q29) Perform basic slicing to extract elements from index 2 to 5(inclusive)from the given Numpy Array.
arr = np.array([1,2,3,4,5,6,7,8,9])
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print("Sliced array:", sliced_array)

Sliced array: [3 4 5 6]


In [ ]:
# Q30) Slice the 2D Numpy array to extract the sub-array [[2,3],[5,6]] from the given array.
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                  [7,8,9]])
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print("Sub-array [[2,3],[5,6]]:")
print(sub_array)

Sub-array [[2,3],[5,6]]:
[[2 3]
 [5 6]]


In [ ]:
# Q31) Write a Numpy function to extract elements in a specific order from a given 2D array based on indices provided in another array.
import numpy as np
def extract_elements_by_indices(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([[0, 1],
                    [1, 2],
                    [2, 0]])
extracted_elements = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements based on the provided indices:")
print(extracted_elements)

Extracted elements based on the provided indices:
[2 6 7]


In [ ]:
# Q32) Create a Numpy function that filters elements greater than a thresold from a given 1D array using boolean indexing.
import numpy as np
def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]
arr = np.array([1, 5, 10, 15, 20, 25])
threshold = 10
filtered_array = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered elements greater than {}: {}".format(threshold, filtered_array))

Filtered elements greater than 10: [15 20 25]


In [ ]:
# Q33) Develop a Numpy function that extracts specific elements from a 3D array using indices provided in three seperate arrays for each dimension.
import numpy as np
def extract_elements_from_3d_array(arr, indices_dim1, indices_dim2, indices_dim3):
    return arr[indices_dim1, indices_dim2, indices_dim3]
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 0, 2])
indices_dim3 = np.array([2, 1, 0])
extracted_elements = extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements from the 3D array based on provided indices:")
print(extracted_elements)

Extracted elements from the 3D array based on provided indices:
[ 6 11 25]


In [ ]:
# Q34) Write a Numpy function Numpy function that returns elements from an array where both the two conditions are satisfied using boolean indexing.
import numpy as np
def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]
arr = np.array([1, 5, 10, 15, 20])
condition1 = arr > 5
condition2 = arr < 15
selected_elements = elements_satisfying_conditions(arr, condition1, condition2)
print("Elements from the array where both conditions are satisfied:", selected_elements)

Elements from the array where both conditions are satisfied: [10]


In [ ]:
# Q35) Write a numpy function that extracts elements from 2D array using row and column indices provided in seperate arrays.
import numpy as np
def extract_elements_from_2d_array(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements from the 2D array based on provided row and column indices:")
print(extracted_elements)

Extracted elements from the 2D array based on provided row and column indices:
[2 6 7]


In [ ]:
# Q36) Given an array arr of shape (3,3) , add a scalar value of 5 to each element using numpy broadcasting.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = arr + 5
print("Original array:")
print(arr)
print("\nArray after adding a scalar value of 5 to each element using broadcasting:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding a scalar value of 5 to each element using broadcasting:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# Q37) Consider two arrays arr1 of shape(1,3) and arr2 of shape(3,4).Multiply each row of arr2 by the corresponding element in arr1 using Numpy broadcasting.
import numpy as np
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
result = arr1 * arr2
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after multiplying each row of arr2 by the corresponding element in arr1:")
print(result)

SyntaxError: invalid syntax (<ipython-input-46-6c98bc9a4135>, line 7)

In [ ]:
# Q38) Given a 1D array arr1 of shape(1,4) and arr2 of shape(4,3).Add arr1 to each row of arr2 using Numpy broadcasting.
import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
result = arr1 + arr2
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after adding arr1 to each row of arr2:")
print(result)

ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

In [ ]:
# Q39) Consider two arrays arr1 of shape(3,1) and arr2 of shape(1,3).Add these arrays using numpy broadcasting.
import numpy as np
arr1 = np.array([[1],
                  [2],
                  [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after adding arr1 to arr2 using broadcasting:")
print(result)

Array arr1:
[[1]
 [2]
 [3]]

Array arr2:
[[4 5 6]]

Result after adding arr1 to arr2 using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# Q40)Given array arr1 of shape(2,3) and arr2 of shape(2,2).Perform Multiplication using Numpy broadcasting.Handle the shape incompatibility.
import numpy as np
arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr2 = np.array([[1, 2],
                  [3, 4]])
arr2_reshaped = arr2.reshape(2, 1, 2)
result = arr1 * arr2_reshaped
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after performing multiplication using broadcasting:")
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,1,2) 

In [ ]:
# Q41) Calculate column-wise mean for the given array:
#arr = np.array([[1,2,3],[4,5,6]])
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print("Array:")
print(arr)
print("\nColumn-wise mean:")
print(column_means)

Array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


In [ ]:
# Q42) Find maximum value in each each row of the given array:
# arr = np.array([[1,2,3],[4,5,6]])
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
max_values_per_row = np.max(arr, axis=1)
print("Array:")
print(arr)
print("\nMaximum value in each row:")
print(max_values_per_row)

Array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


In [ ]:
# Q43) For the given array, find indices of maximum value of each column:
# arr = np.array([[1,2,3],[4,5,6]])
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
max_indices_per_column = np.argmax(arr, axis=0)
print("Array:")
print(arr)
print("\nIndices of maximum value of each column:")
print(max_indices_per_column)

Array:
[[1 2 3]
 [4 5 6]]

Indices of maximum value of each column:
[1 1 1]


In [ ]:
# Q44) For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1,2,3],[4,5,6]])
import numpy as np
def moving_sum(row):
    return np.cumsum(row)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Array:")
print(arr)
print("\nMoving sum along rows:")
print(moving_sum_result)

Array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
# Q45) In the given array, check if all elements in each columns are even.
# arr = np.array([[2,4,6],[3,5,7]])
import numpy as np
arr = np.array([[2, 4, 6],
                [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print("Array:")
print(arr)
print("\nCheck if all elements in each column are even:")
print(all_even_columns)

Array:
[[2 4 6]
 [3 5 7]]

Check if all elements in each column are even:
[False False False]


In [ ]:
# Q46) Given a Numpy array arr, reshape it into a matrix of dimensions'm' rows and 'n' columns. Return the reshaped matrix.
#original_array = np.array([1,2,3,4,5,6])
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = np.reshape(original_array, (m, n))
print("Original array:")
print(original_array)
print("\nReshaped matrix:")
print(reshaped_matrix)

Original array:
[1 2 3 4 5 6]

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Q47) Create a  function that takes a matrix as input and return the flattened array.
input_matrix = np.array = ([1,2,3],[4,5,6])
import numpy as np
def flatten_matrix(input_matrix):
    return input_matrix.flatten()
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print("Input matrix:")
print(input_matrix)
print("\nFlattened array:")
print(flattened_array)

TypeError: tuple indices must be integers or slices, not tuple

In [ ]:
# Q48) Write a function that concentrate two given arrays along a specified axis.
#array1 = np.array([[1,2],[3,4]])
#array2 = np.array([[5,6],[7,8]])
import numpy as np
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])
concatenated_array_rows = concatenate_arrays(array1, array2, axis=0)
concatenated_array_columns = concatenate_arrays(array1, array2, axis=1)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated array along rows:")
print(concatenated_array_rows)
print("\nConcatenated array along columns:")
print(concatenated_array_columns)

TypeError: 'tuple' object is not callable

In [ ]:
# Q49) Create a function that spilts an array into multiple sub-arrays along a specified axis.
#original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
import numpy as np
def split_array(original_array, axis=0):
    return np.split(original_array, indices_or_sections, axis=axis)
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
split_arrays_rows = split_array(original_array, axis=0)
split_arrays_columns = split_array(original_array, axis=1)
print("Original array:")
print(original_array)
print("\nSplit arrays along rows:")
for arr in split_arrays_rows:
    print(arr)
print("\nSplit arrays along columns:")
for arr in split_arrays_columns:
    print(arr)

TypeError: 'tuple' object is not callable

In [ ]:
# Q50) Write a function that inserts and then delete elements from a given array at specified indices.
original_array = np.array([1,2,3,4,5])
indices_to_insert = [2,4]
values_to_insert = [10,11]
indices_to_delete = [1,3]

import numpy as np
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)
    original_array = np.delete(original_array, indices_to_delete)
    return original_array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
updated_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Original array:")
print(original_array)
print("\nUpdated array after inserting and deleting elements:")
print(updated_array)

TypeError: 'tuple' object is not callable

In [ ]:
# Q51) Create a Numpy array "arr1" with random integers and another array "arr2" with integers from 1 to 10.Perform element-wise addition between "arr1" and "arr2".
import numpy as np
arr1 = np.random.randint(1, 100, size=(5, 5))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)
result = arr1 + arr2
print("\nResult of element-wise addition:")
print(result)

TypeError: 'tuple' object is not callable

In [ ]:
# Q52) Generate a numpy array "arr1" with sequential integers from 10 to 1 and another array "arr2" with integers from 1 to 10.Subtract "arr2" from "arr1" element_wise.
import numpy as np
arr1 = np.arange(10, 0, -1)
print("arr1:")
print(arr1)
arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)
result = arr1 - arr2
print("\nResult of element-wise subtraction:")
print(result)

arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
# Q53) Create a Numpy array "arr1" with random integers and another array "arr2" with integers from 1 to 5.Perform element-wise multiplication between "arr1" and "arr2".
import numpy as np
arr1 = np.random.randint(1, 10, size=(3, 3))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)
result = arr1 * arr2
print("\nResult of element-wise multiplication:")
print(result)

TypeError: 'tuple' object is not callable

In [ ]:
# Q54) Generate a numpy array "arr1" with random integers from 2 to 10 and another array "arr2" with integers from 1 to 5.Perform element-wise division of "arr1" by "arr2".
import numpy as np
arr1 = np.random.randint(2, 11, size=(3, 3))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)
result = arr1 / arr2
print("\nResult of element-wise division:")
print(result)

TypeError: 'tuple' object is not callable

In [ ]:
# Q55) Create a Numpy array "arr1" with integers from 1 to 5 and another array "arr2" with the same numbers reversed .Calculate the exponentiation of "arr1" raised to the power of "arr2" element-wise.
import numpy as np
arr1 = np.arange(1, 6)
print("arr1:")
print(arr1)
arr2 = np.flip(arr1)
print("\narr2:")
print(arr2)
result = np.power(arr1, arr2)
print("\nResult of element-wise exponentiation:")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [ ]:
# Q56) Write a function that counts the occurences of a specific substring within a Numpy array of Strings.
arr = np.array(["hello","world","hello","numpy","hello"])
import numpy as np
def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count
arr = np.array(["hello", "world", "hello", "numpy", "hello"])
substring = "hello"
occurrences = count_substring_occurrences(arr, substring)
print("Array:")
print(arr)
print("\nSubstring:", substring)
print("Occurrences:", occurrences)

TypeError: 'tuple' object is not callable

In [ ]:
# Q57) Write a function that extracts uppercase characters from a numpy array of strings.
#arr = np.array(["hello","world","grape","pineapple"])
import numpy as np
def extract_uppercase_characters(arr):
    uppercase_chars = np.array([char for string in arr for char in string if char.isupper()])
    return uppercase_chars
arr = np.array(["hello", "world", "grape", "pineapple"])
uppercase_chars = extract_uppercase_characters(arr)
print("Array:")
print(arr)
print("\nUppercase characters:")
print(uppercase_chars)

TypeError: 'tuple' object is not callable

In [ ]:
# Q58) Write a function that replaces occurences of a substring ina numpy array of strings with a new string.
arr = np.array(["apple","banana","grape","pineapple"])
import numpy as np
def replace_substring(arr, substring, new_substring):
    return np.char.replace(arr, substring, new_substring)
arr = np.array(["apple", "banana", "grape", "pineapple"])
substring = "apple"
new_substring = "orange"
arr_replaced = replace_substring(arr, substring, new_substring)
print("Original array:")
print(arr)
print("\nReplaced array:")
print(arr_replaced)

TypeError: 'tuple' object is not callable

In [ ]:
# Q59) Write a function that concatenates strings in a Numpy array element-size.
# arr1 = np.array(['Hello','World'])
# arr2 = np.array(['open','AI'])
import numpy as np
def concatenate_strings(arr1, arr2):
    return arr1 + arr2
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['open', 'AI'])
concatenated_arr = concatenate_strings(arr1, arr2)
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array:")
print(concatenated_arr)

TypeError: 'tuple' object is not callable

In [ ]:
# Q60) Write a function that finds the length of the longest string in a Numpy array.
# arr = np.array(["apple", "banana", "grape", "pineapple"])
import numpy as np
def longest_string_length(arr):
    string_lengths = np.array([len(string) for string in arr])
    max_length = np.max(string_lengths)
    return max_length
arr = np.array(["apple", "banana", "grape", "pineapple"])
max_length = longest_string_length(arr)
print("Array:")
print(arr)
print("\nLength of the longest string:", max_length)

TypeError: 'tuple' object is not callable

In [ ]:
# Q61) Create a dataset of 100 random integers between 1 and 1000 .Commpute the mean,median,variance,and standard deviation of the dataset using Numpy's Function.
import numpy as np
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Dataset:", dataset)
print("\nMean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

TypeError: 'tuple' object is not callable

In [ ]:
# Q62) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentile of the dataset.
import numpy as np
data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("Data:", data)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

TypeError: 'tuple' object is not callable

In [ ]:
# Q63) Create two arrays representing two sets of variable .Compute the correlation coefficient between these arrays using Numpy's corrcoef function.
import numpy as np
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([5, 4, 3, 2, 1])
correlation_coefficient = np.corrcoef(set1, set2)[0, 1]
print("Set 1:", set1)
print("Set 2:", set2)
print("\nCorrelation Coefficient:", correlation_coefficient)

TypeError: 'tuple' object is not callable

In [ ]:
# Q64) Create two matrices and perform matrix multiplication using Numpy's dot function.
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
result = np.dot(matrix1, matrix2)
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)

TypeError: 'tuple' object is not callable

In [ ]:
# Q65) Create an array of 50 integers between 10 and 1000 .Calculate the 10th, 50th(median), and 90th percentiles along with the first and third quartiles.
import numpy as np
data = np.random.randint(10, 1001, size=50)
percentiles = np.percentile(data, [10, 25, 50, 75, 90])
first_quartile = percentiles[1]
median = percentiles[2]
third_quartile = percentiles[3]
print("Data:", data)
print("\n10th Percentile:", percentiles[0])
print("25th Percentile (First Quartile):", first_quartile)
print("50th Percentile (Median):", median)
print("75th Percentile (Third Quartile):", third_quartile)
print("90th Percentile:", percentiles[4])

TypeError: 'tuple' object is not callable

In [ ]:
# Q66) Create a Numpy array of integers and find the index of a specific element.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
element = 3
indices = np.where(arr == element)
print("Array:", arr)
print("Element to find:", element)
print("Index of element:", indices[0])

TypeError: 'tuple' object is not callable

In [ ]:
# Q67) Generate a random Numpy array and sort it in ascending order.
import numpy as np
random_array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(random_array)
print("Random Array:", random_array)
print("Sorted Array (Ascending Order):", sorted_array)

TypeError: 'tuple' object is not callable

In [ ]:
# Q68) Filter elements >20 in the given Numpy array.
#arr = np.array([12,25,6,42,8,30])
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_arr)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [ ]:
# Q69) Filter elements which are divisible by 3 from a given numpy array.
# arr = np.array([1,5,8,12,15])
import numpy as np
arr = np.array([1,5,8,12,15])
filtered_arr = arr[arr % 3 == 0]
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_arr)

TypeError: 'tuple' object is not callable

In [ ]:
# Q70) Filter elements which are >= 20 and <=40 from a given Numpy Array.
# arr = np.array([10,20,30,40,50])
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (elements between 20 and 40 inclusive):", filtered_arr)

In [ ]:
# Q71) For the given Numpy array , check its byte order using the"dtype" attribute byteorder.
# arr = np.array([1,2,3])
import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

In [ ]:
# Q72) For the given Numpy array, perform byte swapping in place using "byteswap()."
# arr = np.array([1,2,3], dtype = np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print("Swapped Array:", arr)

In [ ]:
# Q73) For the given Numpy array , swap its byte order without modifying the original array using "newbyteorder()."
# arr = np.array([1,2,3],dtype = np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print("Swapped Array:", arr)

In [ ]:
# Q74) For the given Numpy array , swap its byte order conditionally based on system endianness using "newbyteorder()."
# arr = np.array([1,2,3],dtype = np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.newbyteorder()
print("Swapped Array:", arr)

In [ ]:
# Q75) For the given Numpy array,check if byte swapping is necessary for the current system using"dtype" attribute "byteorder()."
# arr = np.array([1,2,3],dtype = np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
if byte_order == '=':
    print("No byte swapping necessary (native byte order)")
else:
    print("Byte swapping is necessary for current system")
print("Byte order:", byte_order)

In [ ]:
# Q76) Create a Numpy array "arr1" with values from 1 and 10. Create a copy of "arr1" named "copy_arr" and modify an element in "copy_arr". Check if modifying "copy_arr"affects "arr1".
import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("arr1:", arr1)
print("copy_arr:", copy_arr)

In [ ]:
# Q77) Create a 2D Numpy  array "matrix"  of shape(3,3) with random integers. Extract a slice"view_slice" from the matrix. Modify an element in "view_slice" and observe if it changes the original "matrix".
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print("Original matrix:")
print(matrix)
print("\nSlice view_slice:")
print(view_slice)

In [ ]:
 # Q78) Create a Numpy array "array_a" of shape (4,3) with sequential integers from 1 to 12. Extract a slice "view_b" from "array_a" and broadcast the addition of 5 to view_b.Check if it alters the original "array_a"
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print("Original array_a:")
print(array_a)
print("\nSlice view_b:")
print(view_b)

In [ ]:
# Q79) create a Numpy array "orig_array" of shape (2,4) with values from 1 to 8. Create a reshaped view "reshaped_view" of shape (4,2) from orig_array.Modify an element in "reshaped_view" and checks if it reflects changes in the original "orig_array"
import numpy as np8
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
print("Original orig_array:")
print(orig_array)
print("\nReshaped view reshaped_view:")
print(reshaped_view)

In [ ]:
# Q80) Create a Numpy array "data" of shape (3,4) with random integers. Extract a copy"data_copy"of elements greater than 5. Modify an elements in "data_copy" and verify if it affects the original "data"
import numpy as np
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0, 0] = 100
print("Original data:")
print(data)
print("\nModified data_copy:")
print(data_copy)

In [ ]:
# Q81) create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
import numpy as np
shape = (3, 3)
A = np.random.randint(1, 10, size=shape)
B = np.random.randint(1, 10, size=shape)
addition_result = A + B
subtraction_result = A - B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)

In [ ]:
# Q82)Generate two matrices "C" (3x2) and "B"(2,4) and perform matrix multiplication.
import numpy as np
C = np.random.randint(1, 10, size=(3, 2))
B = np.random.randint(1, 10, size=(2, 4))
result = np.dot(C, B)
print("Matrix C:")
print(C)
print("\nMatrix B:")
print(B)
print("\nMatrix Multiplication Result (C * B):")
print(result)

In [ ]:
# Q83) Create a matrix "E" and find its transpose.
import numpy as np
E = np.array([[1, 2, 3],
              [4, 5, 6]])
E_transpose = np.transpose(E)
print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)

In [ ]:
# Q84) Generate a square matrix "F" and compute its determinant.
import numpy as np
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
determinant_F = np.linalg.det(F)
print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:", determinant_F)

In [ ]:
# Q85) Create a square matrix "G" and find its inverse.
import numpy as np
G = np.array([[1, 2],
              [3, 4]])
inverse_G = np.linalg.inv(G)
print("Matrix G:")
print(G)
print("\nInverse of Matrix G:")
print(inverse_G)